name: release
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG}}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    steps:
      - uses: actions/checkout@v2
      - name: Create new Sentry release and deploy

        run: |
          # Install Sentry CLI
          curl -sL https://sentry.io/get-cli/ | bash

          # Create new Sentry release
          export SENTRY_LOG_LEVEL=debug
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
          sentry-cli releases set-commits --local $SENTRY_RELEASE
          sentry-cli releases finalize $SENTRY_RELEASE
  
  make-bug:
      name: check outcode
      runs-on: ubuntu-18.04
      env: 
        GITHUB_SHA: $GITHUB_SHA
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
           
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
      
        - name: install requirements
          run: pip install -r requirements.txt

        - name: run python
          run: |
            python script.py $GITHUB_SHA